/**
 * Optimized image paths and blur placeholders.
 * Generated by scripts/optimize-images.mjs — do not edit manually.
 */

// ─── Hero Backgrounds ───────────────────────────────────────────────────────

export const heroImages = {
  "hero-background": {
    webp: "/optimized/hero-background.webp",
    mobile: "/optimized/hero-background-mobile.webp",
    original: "/hero-background.png",
    blurDataUrl:
      "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoUAAsAPzmGulQvKSWjMAgB4CcJQBOiP/wHjcUfytGVhzm9AAD+ozQo81RUtV9u8LWrAY7f3Pbj1T/DvFRAorxWIUS/g/D+amXRoBYxiA4N+xciW81PrBGqyQA1CilsGODYMdIflgfQOVEb3uAAAA==",
  },
  "hero-media-partner": {
    webp: "/optimized/hero-media-partner.webp",
    mobile: "/optimized/hero-media-partner-mobile.webp",
    original: "/hero-media-partner.png",
    blurDataUrl:
      "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJYwCsACHomTjpmpFcXYIAAP6iFAn34sYGfqjw+IroVSIpyvVreFcMvi0hSvW3mVCvJUW/t7bx2ePOuQaIuon48T7HZqN1jIAAAA==",
  },
  "hero-partenaires": {
    webp: "/optimized/hero-partenaires.webp",
    mobile: "/optimized/hero-partenaires-mobile.webp",
    original: "/hero-partenaires.png",
    blurDataUrl:
      "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwBACdASoUAAsAPzmGuVOvKSWisAgB4CcJYwC7Ef/gPKDvC5Ok8S1FB0AA/nkpgakllKG86E2cRR7+9ErUAS016Z6CCxUD9qwQSYttknWhpvT6/eEk0niJdguwPW1Vbc+N+6FlRH4owmdAAAA=",
  },
  "hero-particuliers": {
    webp: "/optimized/hero-particuliers.webp",
    mobile: "/optimized/hero-particuliers-mobile.webp",
    original: "/hero-particuliers.png",
    blurDataUrl:
      "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZACdACFmeRA9BAXAwAD+zU2J3D5c+bXixSdl8BlbIX82KDln+kItfIPMswoDVi7F/KgOVwaRYaLa3XqgAA==",
  },
} as const

// ─── Avatar Images ───────────────────────────────────────────────────────────

export const avatarImages: Record<string, { webp: string; blurDataUrl: string }> = {
  "/CatherineV.jpeg": {
    webp: "/optimized/CatherineV.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoKAAoABUB8JQBOgB+FyaMTaAAAzjCC7rvvb65PaT4uAo61ul4WxetYwK6rkhc5r3CBizpWYgQ+R71IfmjKAAAA",
  },
  "/EmilieS.jpeg": {
    webp: "/optimized/EmilieS.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoKAAoABUB8JQBOgButzJFwAP5MdbTV9lcQggvQdH2I5xySYobeioCIwgghX7p3AIMOH4AA",
  },
  "/FrancoisG.jpeg": {
    webp: "/optimized/FrancoisG.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAoABUB8JQBOgCPqGvQ8kAD+5fNVprSBRlNMklu8liVJMlUgL+8uS4nSYKOxLfgJQEwgAAA=",
  },
  "/IsabelleL.jpeg": {
    webp: "/optimized/IsabelleL.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoKAAoABUB8JYgCdAD5ZMkAAP7swVIIZuA4Qaf1/y9XQrCbcuP/JCRYdDQaPhv2bDnOiAAA",
  },
  "/JeanPierreMartin.jpeg": {
    webp: "/optimized/JeanPierreMartin.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAoABUB8JZACdAELXQaCQAD+wbmHtTnT+hGoccrIAjksnpwDoMfCK3OAvQTqD4ytdj2uAAA=",
  },
  "/LaurenceM.jpeg": {
    webp: "/optimized/LaurenceM.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoKAAoABUB8JZACdACy/LVFFwAA/TsGcOlkg0BIM5PzP/IUQzXxkjA3eGX5ED0/Bbq70FI4RhkEYp6SAAA=",
  },
  "/MichelBernard.jpeg": {
    webp: "/optimized/MichelBernard.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAAoABUB8JQBOgBulSUsLQsAA/kyq01w3yPXv3RkgSVc1Sl7dSZ1OOjmAVE3ENkHaZNUAAAA=",
  },
  "/NathalieP.jpeg": {
    webp: "/optimized/NathalieP.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoKAAoABUB8JQBOgBqxl4AAyi4/czdRbHvR8yYs+lW/pblhLudKolx0C6hfA2jcijygx070jgQAAA==",
  },
  "/PhilippeD.jpeg": {
    webp: "/optimized/PhilippeD.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAoABUB8JQBOgCFdN+eifAD5/ZHnByaLRnFtN2N0fhbS8ijLS3p4Vc5b+Cx4AAA=",
  },
  "/SophieDurand.jpeg": {
    webp: "/optimized/SophieDurand.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAoABUB8JQBOgBks0AwAAP7MV5LfluT0bfOi14rSWnwcm3UKCQmNlXvgGVNgAAA=",
  },
  "/StephanieW.jpeg": {
    webp: "/optimized/StephanieW.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAoABUB8JQBOgBuZ0p0AAP6Hj/igwHGUZ9dxoBbeGBNScivdI8XEeh0tbVoAAAA=",
  },
  "/ThomasR.jpeg": {
    webp: "/optimized/ThomasR.webp",
    blurDataUrl:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoKAAoABUB8JQBOgB+E/szNhmgAAP6Fod63zMeixeEsugLxmLUFaEKBq1KYlw800Han8sgpRgY8oZZyiwAAAA==",
  },
} as const
